FROM python:3.12-slim-bullseye
RUN apt-get update && apt-get install -y git ssh && rm -rf /var/lib/apt/lists/*
RUN mkdir /app
COPY ./src/distopf_federate/ /app
COPY ./requirements.txt /app/
WORKDIR /app
RUN pip install -r requirements.txt
EXPOSE 5903/tcp
CMD ["python", "federate.py"]
